### ISSUE TITLE
how it works?

### ISSUE THREAD

**Issue by Magicwager** [filaraujo/gulp-i18n-localize#5]
Can you give me a simple demo to show how it works ?
I have set the gulpfile.js like this:
gulp.task('i18n', function () {
    return gulp.src('src/**/**')
        .pipe(i18n({
            delimeters: ['!{', '}!'],
            locales: ['en','zh_CN'],
            localeDir: './locale'
        }))
        .pipe(gulp.dest('dist'));
});
and then I use it in the javascript  file like this:  console.log(!{'solution'}!),
but it doesn't work and show there is no translation.

**Comment by itmm** [comment]
You have to put your json files into the subdirectories (e.g. ./locale/zh_CN/x.json). If you have key y in file x.json, you have to refer to it as !{ x.y }! in your code.

Hope that helps, it worked for me :-)

**Comment by marekparal** [comment]
And the way to build json files... only manual?

**Comment by itmm** [comment]
Yes, that was sufficient for me.

Kind regards,
Timm.

**Comment by filaraujo** [comment]
Thanks for helping @itmm, I added some more documentation that hopefully can help future users.

https://github.com/filaraujo/gulp-i18n-localize#file-structure
