### ISSUE TITLE
Translation for the main index.html

### ISSUE THREAD

**Issue by wawanzs** [filaraujo/gulp-i18n-localize#7]
Say, if I have 3 different languages for a site; `lang-1`, `lang-2`, and `lang-3`. Is it possible to make the `lang-1` as the translation for main index.html? Like, when the user go to example.com they'll see translation from `lang-1`. 
Right now, my main index.html is showing the `${{ translation.content.example }}$`

```
<url>/index.html (the main index file with lang-1)
<url>/lang-2/index.html
<url>/lang-3/index.html
```

Thank you.

**Comment by filaraujo** [comment]
Sounds like your best bet is to have another gulp process after translation
move the lang-1 folder into the root.

`gulp.src($LANG-1-PATH).pipe(gulp.dest(ROOT));` something similar to this

**Comment by wawanzs** [comment]
I was thinking of doing the same too. Thanks man!
